env:
  global:
    - CC_TEST_REPORTER_ID=6b8f4e907689aa3e7f1020c3a369722fcaecd836651e1073c49913637c829623
language: node_js
node_js:
  - "12"
cache:
  directories:
    - "node_modules"
before_install:
  - npm install -g webpack
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run test-with-coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
