language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

before_install:
  - npm install -g webpack
  - npm install -g casperjs

before_script:
  - casperjs --version; phantomjs --version;
  - npm run test